"""Blog post registry. One entry per post; chips lists the "Tools we reach for"
chip labels (on any service page) that link to the post. Slug = /blog/<slug>.
type: 'concept' (plain-English explainer) or 'guide' (step-by-step tutorial).
"""

DATE = 'July 2026'
DATE_ISO = '2026-07-01'  # machine-readable form of DATE for JSON-LD / sitemap lastmod

POSTS = [
    # ---------------- it-support (red) ----------------
    dict(slug='microsoft-365-small-business', lane='it-support', type='concept',
         title='Microsoft 365 for small business: what you actually need',
         description='Business Basic, Standard, or Premium? What each Microsoft 365 plan includes and which one most small businesses should buy.',
         chips=['Microsoft 365']),
    dict(slug='google-workspace-vs-microsoft-365', lane='it-support', type='concept',
         title='Google Workspace or Microsoft 365? How to pick',
         description='An honest comparison for small teams: mail, files, meetings, price, and the switching cost nobody mentions.',
         chips=['Google Workspace']),
    dict(slug='windows-and-mac-one-office', lane='it-support', type='concept',
         title='Running Windows and Mac in one office',
         description='Mixed fleets are normal now. How we manage both without doubling the work.',
         chips=['Windows & Mac']),
    dict(slug='what-is-remote-monitoring', lane='it-support', type='concept',
         title='Remote monitoring, explained: how we see problems before you do',
         description='What RMM software watches, what alerts mean, and why the quiet fixes are the ones you pay for.',
         chips=['Remote monitoring']),
    dict(slug='automated-patching', lane='it-support', type='concept',
         title='Automated patching: the boring habit that prevents ugly weeks',
         description='Most breaches exploit patches released months earlier. How automated patching works and what we patch first.',
         chips=['Automated patching']),
    dict(slug='what-good-help-desk-looks-like', lane='it-support', type='concept',
         title='What good help desk looks like (a person answers)',
         description='Ticket queues, SLAs, and why the metric that matters is time-to-human.',
         chips=['Help desk tooling']),
    dict(slug='device-management-basics', lane='it-support', type='concept',
         title='Device management basics: MDM without the acronym soup',
         description='Intune, profiles, and remote wipe: what managing company devices actually means.',
         chips=['Device management']),
    dict(slug='onboarding-offboarding-checklist', lane='it-support', type='guide',
         title='The employee IT onboarding and offboarding checklist we use',
         description='Accounts, devices, licenses, and access, in order. Copy this checklist before your next hire or exit.',
         chips=['Onboarding & offboarding']),
    dict(slug='spf-dkim-dmarc-setup', lane='it-support', type='guide',
         title='Set up SPF, DKIM, and DMARC records that actually pass',
         description='Step-by-step DNS records that stop spoofing and keep your mail out of spam folders.',
         chips=['Email security', 'Spam filtering']),
    dict(slug='321-backup-rule', lane='it-support', type='concept',
         title='The 3-2-1 backup rule, and why restore is the part that matters',
         description='Three copies, two media, one offsite. And the restore drill most businesses skip.',
         chips=['Backup & restore']),
    dict(slug='software-license-management', lane='it-support', type='concept',
         title='License management: stop paying for seats nobody uses',
         description='The audit that usually finds 20% waste in software spend, and how to keep it from creeping back.',
         chips=['License management']),
    dict(slug='it-vendor-management', lane='it-support', type='concept',
         title='Vendor wrangling: one throat to choke for ISP calls',
         description='ISPs, printer leases, software renewals. Why one owner for vendor calls saves hours and money.',
         chips=['Vendor wrangling', 'Warranty & procurement']),
    dict(slug='it-asset-tracking', lane='it-support', type='concept',
         title='Asset tracking: know what you own and where it is',
         description='Serial numbers, warranties, and assignment records. The boring list that saves you at tax time and exit time.',
         chips=['Asset tracking']),
    dict(slug='troubleshoot-network-printer', lane='it-support', type='guide',
         title='Troubleshoot a network printer like a tech',
         description='The diagnostic order we use: driver, queue, IP, VLAN, firmware. Fix it in minutes instead of rebooting everything twice.',
         chips=['Printer & peripheral duty']),
    dict(slug='it-documentation', lane='it-support', type='concept',
         title='IT documentation: the cheapest insurance you can buy',
         description='Network maps, passwords, and runbooks. What to document, where to keep it, and who gets access.',
         chips=['Documentation', 'Labeling & documentation']),
    dict(slug='server-care-basics', lane='it-support', type='concept',
         title='Server care: what maintaining a server actually involves',
         description='Updates, disk health, backup checks, and logs. The monthly routine that keeps servers boring.',
         chips=['Server care']),

    # ---------------- cloud (yellow) ----------------
    dict(slug='azure-vs-aws-vs-google-cloud', lane='cloud', type='concept',
         title='Azure, AWS, or Google Cloud: an honest comparison',
         description='Where each cloud wins for small and mid-size businesses, and why the answer is usually the one your stack already leans toward.',
         chips=['Azure', 'AWS', 'Google Cloud']),
    dict(slug='what-cloudflare-does', lane='cloud', type='concept',
         title='What Cloudflare actually does for your website',
         description='DNS, CDN, DDoS protection, and Workers, in plain English.',
         chips=['Cloudflare']),
    dict(slug='terraform-first-project', lane='cloud', type='guide',
         title='Your first Terraform project: one server on AWS',
         description='Install Terraform, write your first config, plan, apply, destroy. Infrastructure as code from zero.',
         chips=['Terraform']),
    dict(slug='do-you-need-kubernetes', lane='cloud', type='concept',
         title='You probably don’t need Kubernetes',
         description='What Kubernetes solves, what it costs in complexity, and the simpler options that fit most businesses.',
         chips=['Kubernetes']),
    dict(slug='install-docker-ubuntu', lane='cloud', type='guide',
         title='Install Docker on Ubuntu and run your first container',
         description='Repository setup, install, permissions, hello-world, and a real service in a container.',
         chips=['Docker']),
    dict(slug='lift-and-shift-explained', lane='cloud', type='concept',
         title='Lift-and-shift, explained: move servers to the cloud without rewriting',
         description='When rehosting beats rebuilding, what changes after the move, and the gotchas we plan around.',
         chips=['Lift-and-shift migrations']),
    dict(slug='zero-downtime-cutovers', lane='cloud', type='concept',
         title='How we cut over systems without downtime',
         description='Parallel runs, DNS TTLs, rollback plans. The playbook for switching systems while the business keeps running.',
         chips=['Zero-downtime cutovers']),
    dict(slug='hybrid-cloud-small-business', lane='cloud', type='concept',
         title='Hybrid cloud for small business: keep the server, add the cloud',
         description='Some things belong in the closet, some in the cloud. How to split them sensibly.',
         chips=['Hybrid cloud']),
    dict(slug='cloud-cost-optimization', lane='cloud', type='concept',
         title='Why your cloud bill is high, and how we shrink it',
         description='Right-sizing, reserved pricing, orphaned resources, and egress. Where the waste hides and how to cut it.',
         chips=['Cost optimization', 'Right-sizing', 'Reserved pricing']),
    dict(slug='cloud-backup-disaster-recovery', lane='cloud', type='concept',
         title='Cloud backups and disaster recovery: the plan you hope you never use',
         description='RPO, RTO, and what a realistic DR plan costs at small-business scale.',
         chips=['Cloud backups', 'Disaster recovery']),
    dict(slug='what-is-serverless', lane='cloud', type='concept',
         title='Serverless, explained: paying for work instead of waiting',
         description='Functions, cold starts, and when serverless is cheaper than a server that idles all night.',
         chips=['Serverless']),
    dict(slug='host-static-site-cloudflare-workers', lane='cloud', type='guide',
         title='Host a static site on Cloudflare Workers',
         description='Wrangler setup, assets config, custom domain, and deploy. A fast site with no server to babysit.',
         chips=['Storage & CDN']),
    dict(slug='wireguard-site-to-site-vpn', lane='cloud', type='guide',
         title='Set up a WireGuard VPN between two offices',
         description='Keys, configs, routing, and firewall rules for a fast site-to-site tunnel.',
         chips=['VPNs & private networking']),
    dict(slug='identity-access-basics', lane='cloud', type='concept',
         title='Identity and access: one login, fewer passwords, less risk',
         description='SSO, roles, and least privilege, explained for people who just want fewer password resets.',
         chips=['Identity & access']),
    dict(slug='uptime-monitoring-alerts', lane='cloud', type='guide',
         title='Set up uptime monitoring and alerts that wake the right person',
         description='Health checks, status pages, and escalation. Know your site is down before your customers tell you.',
         chips=['Monitoring & alerts']),
    dict(slug='new-ubuntu-server-checklist', lane='cloud', type='guide',
         title='First 30 minutes on a new Ubuntu server',
         description='Users, SSH keys, firewall, fail2ban, and updates. The hardening checklist we run on every fresh box.',
         chips=['Linux & Windows servers']),
    dict(slug='email-migration-guide', lane='cloud', type='concept',
         title='Email migration without losing a single message',
         description='Cutover vs staged migration, MX timing, and the archive question. How mailbox moves go smoothly.',
         chips=['Email migration']),

    # ---------------- cybersecurity (green) ----------------
    dict(slug='what-is-edr', lane='cybersecurity', type='concept',
         title='EDR, XDR, antivirus: what actually protects endpoints now',
         description='Signatures are dead. What modern endpoint protection watches for and why detection beats prevention alone.',
         chips=['EDR/XDR', 'Endpoint protection', 'Microsoft Defender']),
    dict(slug='who-watches-at-3am', lane='cybersecurity', type='concept',
         title='Who’s watching your network at 3 a.m.?',
         description='What 24/7 monitoring and threat hunting actually involve, and what size business needs them.',
         chips=['24/7 monitoring', 'Threat hunting']),
    dict(slug='ransomware-defense-layers', lane='cybersecurity', type='concept',
         title='Ransomware defense: the five layers that matter',
         description='Email filtering, patching, EDR, backups, and training. Why no single product saves you.',
         chips=['Ransomware defense']),
    dict(slug='test-your-backups', lane='cybersecurity', type='guide',
         title='How to actually test your backups: a restore drill',
         description='Pick a file, a folder, and a full system. Restore all three, time it, and write down what broke.',
         chips=['Tested backups']),
    dict(slug='first-24-hours-after-breach', lane='cybersecurity', type='concept',
         title='The first 24 hours after a breach: what to do, in order',
         description='Isolate, preserve, notify, recover. The incident response sequence, before you need it.',
         chips=['Incident response']),
    dict(slug='phishing-training-that-works', lane='cybersecurity', type='concept',
         title='Phishing training that people don’t hate',
         description='Simulations, not shame. How to build click-awareness without turning IT into the villain.',
         chips=['Phishing simulations', 'Security training']),
    dict(slug='mfa-rollout-guide', lane='cybersecurity', type='guide',
         title='Roll out MFA to a small business without a mutiny',
         description='App-based codes, hardware keys, and the rollout order that gets adoption instead of eye-rolls.',
         chips=['MFA everywhere']),
    dict(slug='password-manager-rollout', lane='cybersecurity', type='guide',
         title='Set up a company password manager the right way',
         description='Vault structure, sharing, emergency access, and the migration from the spreadsheet nobody admits exists.',
         chips=['Password managers']),
    dict(slug='what-is-zero-trust', lane='cybersecurity', type='concept',
         title='Zero trust, minus the buzzwords',
         description='Verify every request, trust no network. What zero trust means in practice for a 20-person company.',
         chips=['Zero trust']),
    dict(slug='what-firewalls-do', lane='cybersecurity', type='concept',
         title='What your firewall actually does (and what it can’t)',
         description='Ports, rules, and inspection. Why a firewall is necessary but nowhere near sufficient.',
         chips=['Firewalls']),
    dict(slug='do-you-need-a-vpn', lane='cybersecurity', type='concept',
         title='Do you still need a VPN?',
         description='Remote access VPNs vs zero-trust access, and what we set up for small teams today.',
         chips=['VPNs']),
    dict(slug='vuln-scan-vs-pentest', lane='cybersecurity', type='concept',
         title='Vulnerability scans vs penetration tests: which first',
         description='One is a smoke detector, one is a break-in drill. Costs, cadence, and which your insurer actually wants.',
         chips=['Vulnerability scanning', 'Penetration testing']),
    dict(slug='dark-web-monitoring', lane='cybersecurity', type='concept',
         title='Dark web monitoring: useful signal or scare tactic?',
         description='What credential monitoring actually finds and what to do when your domain shows up.',
         chips=['Dark web monitoring']),
    dict(slug='hipaa-it-checklist', lane='cybersecurity', type='concept',
         title='HIPAA IT compliance: the checklist without the lawyer bill',
         description='Access controls, encryption, audit logs, and BAAs. The technical safeguards, in plain English.',
         chips=['HIPAA']),
    dict(slug='pci-dss-small-business', lane='cybersecurity', type='concept',
         title='PCI DSS for small business: what taking cards commits you to',
         description='SAQ types, network segmentation, and the shortcuts that make compliance manageable.',
         chips=['PCI DSS']),
    dict(slug='soc2-prep', lane='cybersecurity', type='concept',
         title='SOC 2 prep without the panic',
         description='Trust criteria, evidence collection, and the 6-month runway. What Type I and Type II actually require.',
         chips=['SOC 2 prep']),
    dict(slug='nist-csf-small-business', lane='cybersecurity', type='concept',
         title='NIST CSF: a map, not a mandate',
         description='Identify, protect, detect, respond, recover. Using the framework to find your gaps without drowning in it.',
         chips=['NIST CSF']),
    dict(slug='okta-vs-entra', lane='cybersecurity', type='concept',
         title='Okta vs Microsoft Entra: picking an identity provider',
         description='If you live in Microsoft 365 the answer is usually Entra. When Okta earns its price.',
         chips=['Okta']),

    # ---------------- software (blue) ----------------
    dict(slug='why-typescript', lane='software', type='concept',
         title='Why we build in TypeScript',
         description='Types catch the bugs your tests miss. Why TypeScript is our default for anything past a script.',
         chips=['JavaScript/TypeScript']),
    dict(slug='python-business-automation', lane='software', type='concept',
         title='Python: the duct tape of business automation',
         description='Reports, file moves, API glue. Why Python is usually the fastest path from annoyance to automation.',
         chips=['Python']),
    dict(slug='when-react-makes-sense', lane='software', type='concept',
         title='When React makes sense (and when plain HTML wins)',
         description='Interactive app? React. Marketing site? Static HTML. How we decide, and what it means for your budget.',
         chips=['React']),
    dict(slug='build-rest-api-node', lane='software', type='guide',
         title='Build a REST API with Node.js and Express',
         description='Project setup, routes, middleware, error handling, and deployment. A working API from an empty folder.',
         chips=['Node.js', 'REST APIs']),
    dict(slug='postgres-backup-pgdump', lane='software', type='guide',
         title='Back up and restore PostgreSQL with pg_dump',
         description='Logical dumps, compressed formats, scheduled backups with cron, and the restore you should rehearse.',
         chips=['PostgreSQL']),
    dict(slug='rest-vs-graphql', lane='software', type='concept',
         title='REST or GraphQL: how we choose',
         description='Most business apps want REST. Where GraphQL earns its complexity.',
         chips=['GraphQL']),
    dict(slug='web-app-vs-website', lane='software', type='concept',
         title='Web app or website: which are you actually asking for?',
         description='One shows information, one does work. Why the distinction changes the price by 10x.',
         chips=['Web apps']),
    dict(slug='mobile-app-options', lane='software', type='concept',
         title='Native, React Native, or just a good website?',
         description='Most businesses asking for an app need a responsive site. When a real app is worth the store hassle.',
         chips=['Mobile apps']),
    dict(slug='internal-tools-that-pay', lane='software', type='concept',
         title='The internal tool that pays for itself',
         description='A form that replaces a spreadsheet-and-email loop can save hours a week. How we scope small tools with real ROI.',
         chips=['Internal tools', 'Custom tooling']),
    dict(slug='customer-portal-basics', lane='software', type='concept',
         title='Customer portals: let clients help themselves',
         description='Status, invoices, documents, requests. What a portal should do first and what to leave for phase two.',
         chips=['Customer portals']),
    dict(slug='system-integrations', lane='software', type='concept',
         title='System integrations: make your apps talk to each other',
         description='APIs, webhooks, and middle layers. How we stop the re-typing between systems.',
         chips=['Integrations']),
    dict(slug='workflow-automation-examples', lane='software', type='concept',
         title='Workflow automation: five real examples from real businesses',
         description='Invoice routing, lead intake, report generation, inventory alerts, onboarding packets. What automation looks like in practice.',
         chips=['Workflow automation', 'Process automation']),
    dict(slug='ai-features-without-hype', lane='software', type='concept',
         title='Adding AI to your app without the hype',
         description='Summarize, extract, draft, classify. The four AI features that reliably work and how to ship one safely.',
         chips=['AI features']),
    dict(slug='stripe-checkout-guide', lane='software', type='guide',
         title='Take payments with Stripe Checkout',
         description='Products, checkout sessions, webhooks, and test mode. Payments in an afternoon, done correctly.',
         chips=['Payments']),
    dict(slug='twilio-sendgrid-alerts', lane='software', type='guide',
         title='Send SMS and email alerts from your app',
         description='Twilio for texts, SendGrid for email. API keys, first sends, and the delivery pitfalls to avoid.',
         chips=['Text & email alerts']),
    dict(slug='github-actions-cicd', lane='software', type='guide',
         title='Set up CI/CD with GitHub Actions',
         description='A workflow file that tests every push and deploys on merge. Automation your future self will thank you for.',
         chips=['CI/CD']),
    dict(slug='where-to-host-your-app', lane='software', type='concept',
         title='Where to host your app: VPS, PaaS, or serverless',
         description='A $6 VPS, a platform that deploys from git, or functions that scale to zero. Honest tradeoffs.',
         chips=['Cloud hosting']),
    dict(slug='legacy-software-rescue', lane='software', type='concept',
         title='Rescuing legacy software: modernize without the rewrite',
         description='The full rewrite usually fails. Strangler patterns, API wrappers, and incremental rescue that ships.',
         chips=['Legacy rescues', 'Legacy app rescues']),
    dict(slug='data-migration-planning', lane='software', type='concept',
         title='Data migrations: the plan that prevents the horror story',
         description='Mapping, cleaning, dry runs, and cutover. How data moves between systems without losing rows.',
         chips=['Data migrations']),
    dict(slug='testing-qa-small-apps', lane='software', type='concept',
         title='Testing that fits a small app budget',
         description='You don’t need 100% coverage. The tests that catch real regressions and the ones that waste money.',
         chips=['Testing & QA']),

    # ---------------- networks (red) ----------------
    dict(slug='why-ubiquiti', lane='networks', type='concept',
         title='Why we reach for Ubiquiti in small offices',
         description='Enterprise features at small-business prices, one controller, no license fees. And its honest limits.',
         chips=['Ubiquiti']),
    dict(slug='cisco-meraki-ubiquiti', lane='networks', type='concept',
         title='Cisco, Meraki, or Ubiquiti: matching gear to the job',
         description='License costs, cloud management, and support. Which gear tier your office actually needs.',
         chips=['Cisco', 'Meraki']),
    dict(slug='pfsense-firewall-setup', lane='networks', type='guide',
         title='Set up a pfSense firewall for a small office',
         description='Installation, WAN/LAN setup, firewall rules, and the first five things to configure after install.',
         chips=['pfSense']),
    dict(slug='vlans-explained', lane='networks', type='concept',
         title='VLANs, explained like a floor plan',
         description='One switch, separate networks. Why guest Wi-Fi, cameras, and payments should never share a room.',
         chips=['VLANs']),
    dict(slug='business-wifi-design', lane='networks', type='concept',
         title='Business Wi-Fi that reaches the back office',
         description='AP placement, channels, and coverage mapping. Why more access points on lower power beats one loud one.',
         chips=['Business Wi-Fi', 'Wi-Fi coverage mapping']),
    dict(slug='cabling-done-right', lane='networks', type='concept',
         title='Cat6, fiber, and doing cable runs right the first time',
         description='When copper is fine, when fiber is worth it, and why cheap cabling is the most expensive option.',
         chips=['Fiber & Cat6', 'Structured cabling']),
    dict(slug='clean-network-rack', lane='networks', type='guide',
         title='Build a clean network rack: layout, labeling, patch panels',
         description='Rack order, cable management, labeling scheme, and photos. The closet the next tech thanks you for.',
         chips=['Rack builds', 'Patch panels']),
    dict(slug='server-room-checklist', lane='networks', type='concept',
         title='The server room checklist: cooling, power, access',
         description='Temperature, UPS runtime, physical access, and fire suppression. What a proper closet needs.',
         chips=['Server rooms']),
    dict(slug='cameras-access-control', lane='networks', type='concept',
         title='Cameras and access control on your own network',
         description='PoE cameras, NVRs, badge systems, and why surveillance gear belongs on its own VLAN.',
         chips=['Cameras & access control']),
    dict(slug='voip-for-business', lane='networks', type='concept',
         title='VoIP for small business: what changes, what it costs',
         description='Desk phones, softphones, and call flows. Moving off the phone company without dropping calls.',
         chips=['VoIP phones']),
    dict(slug='failover-internet', lane='networks', type='concept',
         title='Failover internet: stay online when your ISP isn’t',
         description='Dual-WAN routers, LTE backup, and automatic failover. Business continuity for a few dollars a day.',
         chips=['Failover internet']),
    dict(slug='switches-and-routers', lane='networks', type='concept',
         title='Switches and routers: what each box actually does',
         description='Routing, switching, and where the firewall fits. The 10-minute mental model of your network.',
         chips=['Switching & routing']),
    dict(slug='do-you-need-active-directory', lane='networks', type='concept',
         title='Do you still need Active Directory?',
         description='On-prem AD, Entra ID, or nothing at all. How identity management looks for small offices now.',
         chips=['Windows Server', 'Active Directory']),
    dict(slug='virtualization-2026', lane='networks', type='concept',
         title='Virtualization in 2026: Proxmox, VMware, and bare metal',
         description='VMware’s pricing pushed small business to Proxmox. What virtualizing your servers buys you.',
         chips=['Virtualization']),
    dict(slug='nas-private-cloud', lane='networks', type='concept',
         title='NAS for small business: your own private cloud',
         description='Shared drives, snapshots, and offsite sync. When a NAS beats cloud storage bills.',
         chips=['NAS & storage']),
    dict(slug='ups-power-protection', lane='networks', type='concept',
         title='UPS and power: the $200 box that saves the $20,000 server',
         description='Runtime math, clean shutdowns, and surge protection. Power is the outage cause everyone forgets.',
         chips=['UPS & power']),

    # ---------------- data-ai (yellow) ----------------
    dict(slug='first-power-bi-dashboard', lane='data-ai', type='guide',
         title='Build your first Power BI dashboard from a spreadsheet',
         description='Import, model, chart, publish. A working dashboard from the Excel file you already have.',
         chips=['Power BI']),
    dict(slug='looker-studio-dashboards', lane='data-ai', type='guide',
         title='Free dashboards with Looker Studio',
         description='Connect Google Sheets or Analytics, build charts, share with the team. Zero-dollar reporting, step by step.',
         chips=['Looker Studio']),
    dict(slug='sql-still-runs-business', lane='data-ai', type='concept',
         title='SQL: the 40-year-old skill that still runs your business',
         description='Every system you own speaks SQL underneath. Why a few queries beat hours of spreadsheet exports.',
         chips=['SQL']),
    dict(slug='excel-becomes-database', lane='data-ai', type='concept',
         title='When your Excel file becomes a database problem',
         description='The 40-tab workbook everyone fears. Signs the spreadsheet outgrew itself and what graduation looks like.',
         chips=['Excel (no shame)', 'Spreadsheet rescues']),
    dict(slug='dashboards-people-open', lane='data-ai', type='concept',
         title='Dashboards people actually open',
         description='One page, five numbers, updated live. Why most dashboards die and how we build ones that stick.',
         chips=['Live dashboards', 'KPI reporting', 'Dashboards']),
    dict(slug='forecasting-from-your-data', lane='data-ai', type='concept',
         title='Forecasting from your own data: simpler than you think',
         description='Seasonality, trends, and honest error bars. Useful forecasts without a data science team.',
         chips=['Forecasting']),
    dict(slug='data-cleanup-first', lane='data-ai', type='concept',
         title='Data cleanup: why every analytics project starts here',
         description='Duplicate customers, three date formats, mystery columns. Cleaning is 80% of the work and worth every hour.',
         chips=['Data cleanup']),
    dict(slug='do-you-need-data-warehouse', lane='data-ai', type='concept',
         title='Do you need a data warehouse yet?',
         description='When reports across systems get painful, a warehouse helps. What it is and the size where it makes sense.',
         chips=['Data warehouses']),
    dict(slug='etl-pipelines-explained', lane='data-ai', type='concept',
         title='ETL pipelines, explained with a coffee run',
         description='Extract, transform, load. How data moves from your systems into reports without hand-copying.',
         chips=['ETL pipelines']),
    dict(slug='first-claude-api-feature', lane='data-ai', type='guide',
         title='Build your first LLM feature with the Claude API',
         description='API key, first call, prompt structure, and a working document summarizer in under an hour.',
         chips=['Claude & LLM APIs']),
    dict(slug='ai-assistants-that-help', lane='data-ai', type='concept',
         title='AI assistants that actually help (and the ones that don’t)',
         description='Where assistants save real hours: drafts, lookups, triage. And where they quietly make work.',
         chips=['AI assistants']),
    dict(slug='pdfs-into-data', lane='data-ai', type='concept',
         title='Turn PDFs into data: document processing with AI',
         description='Invoices, forms, and contracts into spreadsheet rows. What document AI gets right and where humans stay in the loop.',
         chips=['Document processing']),
    dict(slug='five-numbers-to-watch', lane='data-ai', type='concept',
         title='The five numbers every small business should watch',
         description='Cash position, pipeline, utilization, churn, and margin by job. Simple analytics that change decisions.',
         chips=['Customer analytics', 'Sales & inventory data', 'Plain-English reports']),

    # ---------------- digital (green) ----------------
    dict(slug='sharepoint-without-sprawl', lane='digital', type='concept',
         title='SharePoint without the sprawl',
         description='Site structure, permissions, and naming that hold up past year one. Fixing the folder chaos for good.',
         chips=['SharePoint', 'Document management']),
    dict(slug='slack-or-teams', lane='digital', type='concept',
         title='Slack or Teams: pick one, set it up right',
         description='Channel structure, notification hygiene, and why running both is the worst answer.',
         chips=['Teams', 'Slack', 'Slack & Teams']),
    dict(slug='first-power-automate-flow', lane='digital', type='guide',
         title='Your first Power Automate flow: an approval that emails itself',
         description='Trigger, condition, approval, notification. Kill one email chain today, step by step.',
         chips=['Power Automate']),
    dict(slug='zapier-make-automation', lane='digital', type='guide',
         title='Automate the boring stuff with Zapier or Make',
         description='Connect the form to the sheet to the email. Your first three zaps and when Make’s pricing wins.',
         chips=['Zapier/Make']),
    dict(slug='airtable-grown-up-spreadsheet', lane='digital', type='concept',
         title='Airtable: when a spreadsheet needs to grow up',
         description='Linked records, views, and forms. The middle ground between Excel and custom software.',
         chips=['Airtable']),
    dict(slug='getting-off-paper', lane='digital', type='concept',
         title='Getting off paper: forms, signatures, and workflows',
         description='Digital forms, e-signatures, and routing. Where the paper habit costs you and the painless way out.',
         chips=['Paper-to-digital', 'E-signatures']),
    dict(slug='approval-workflows', lane='digital', type='concept',
         title='Approval workflows: kill the email chain',
         description='Requests, approvers, and audit trails in one place. Nobody hunts through inboxes for the yes.',
         chips=['Approvals & workflows']),
    dict(slug='intranet-small-business', lane='digital', type='concept',
         title='A small-business intranet that people actually use',
         description='One home page for the team: links, announcements, documents. Simple beats fancy here.',
         chips=['Intranets']),
    dict(slug='scheduling-booking-tools', lane='digital', type='concept',
         title='Scheduling tools: stop playing calendar tennis',
         description='Booking pages, round-robins, and reminders. The 30-minute setup that ends the back-and-forth.',
         chips=['Scheduling & booking']),
    dict(slug='quickbooks-integrations', lane='digital', type='concept',
         title='Connect QuickBooks to everything else',
         description='Invoices from your CRM, hours from your PM tool, receipts from your bank. Bookkeeping without re-typing.',
         chips=['QuickBooks integrations']),
    dict(slug='new-tools-that-stick', lane='digital', type='concept',
         title='New tools stick when people like them',
         description='Training, champions, and killing the old way. Change management for teams of ten, not ten thousand.',
         chips=['Change management', 'Training & rollout', 'Training & handoff']),

    # ---------------- staffing (blue) ----------------
    dict(slug='w2-vs-1099-techs', lane='staffing', type='concept',
         title='W-2 or 1099: hiring techs without the compliance headache',
         description='Control, tools, and schedule decide the classification, not preference. What misclassification costs.',
         chips=['W-2 or 1099', 'Payroll handled']),
    dict(slug='contract-vs-direct-hire', lane='staffing', type='concept',
         title='Contract, contract-to-hire, or direct: which fits',
         description='Project work wants contracts. Core roles want direct hires. The decision tree we walk clients through.',
         chips=['Direct hire', 'Contract crews', 'Contract-to-hire', 'Temp-to-perm']),
    dict(slug='hiring-help-desk-techs', lane='staffing', type='concept',
         title='What to look for when hiring help desk techs',
         description='Patience beats certifications. The screening questions that predict who your users will love.',
         chips=['Help desk techs']),
    dict(slug='hiring-sysadmins-network-engineers', lane='staffing', type='concept',
         title='Hiring sysadmins and network engineers: questions that matter',
         description='Scenario questions beat trivia. How we vet infrastructure people before they touch yours.',
         chips=['Sysadmins', 'Network engineers']),
    dict(slug='hiring-developers-not-technical', lane='staffing', type='concept',
         title='Hiring developers when you’re not technical',
         description='Portfolio walkthroughs, paid trials, and red flags. How to hire a dev you can’t personally evaluate.',
         chips=['Developers']),
    dict(slug='multi-site-rollouts', lane='staffing', type='concept',
         title='Staffing multi-site rollouts: field techs in 50 states',
         description='One crew or fifty locals? How national rollouts get staffed, scheduled, and quality-checked.',
         chips=['Field techs', 'Cabling crews', 'Project rollouts', 'Nationwide coverage', 'Managed teams']),
    dict(slug='techs-screen-techs', lane='staffing', type='concept',
         title='Why techs should screen techs',
         description='Keyword-matching recruiters pass people who can’t subnet. What technical screening by practitioners catches.',
         chips=['Tech-led screening', 'Skills testing']),
    dict(slug='background-checks-it-hires', lane='staffing', type='concept',
         title='Background checks for IT hires: what to run and why',
         description='These people hold your passwords. The checks that matter for privileged access, and the ones that are theater.',
         chips=['Background checks']),
    dict(slug='when-your-it-person-quits', lane='staffing', type='concept',
         title='When your only IT person quits: backfill fast',
         description='Lock down access, capture knowledge, bridge the gap. The two-week plan that keeps the lights on.',
         chips=['Backfill coverage', 'Same-week placements']),
]

LANES = {
    'it-support': ('01', 'red', 'IT Support & Managed Services'),
    'cloud': ('02', 'yellow', 'Cloud Setup & Migration'),
    'cybersecurity': ('03', 'green', 'Cybersecurity'),
    'software': ('04', 'blue', 'Custom Software'),
    'networks': ('05', 'red', 'Networks & Infrastructure'),
    'data-ai': ('06', 'yellow', 'Data & AI Analytics'),
    'digital': ('07', 'green', 'Digital Transformation'),
    'staffing': ('08', 'blue', 'Staffing & Recruiting'),
}

# chip label -> post slug (a chip label maps to one post, on every page it appears)
CHIP_TO_SLUG = {}
for _p in POSTS:
    for _c in _p['chips']:
        CHIP_TO_SLUG.setdefault(_c, _p['slug'])

# Featured cards: 3 per service page + 3 for the home page
FEATURED = {
    'home': ['spf-dkim-dmarc-setup', 'ransomware-defense-layers', 'excel-becomes-database'],
    'it-support': ['onboarding-offboarding-checklist', 'what-is-remote-monitoring', '321-backup-rule'],
    'cloud': ['cloud-cost-optimization', 'terraform-first-project', 'new-ubuntu-server-checklist'],
    'cybersecurity': ['test-your-backups', 'mfa-rollout-guide', 'vuln-scan-vs-pentest'],
    'software': ['web-app-vs-website', 'internal-tools-that-pay', 'stripe-checkout-guide'],
    'networks': ['vlans-explained', 'clean-network-rack', 'business-wifi-design'],
    'data-ai': ['dashboards-people-open', 'first-power-bi-dashboard', 'first-claude-api-feature'],
    'digital': ['first-power-automate-flow', 'getting-off-paper', 'slack-or-teams'],
    'staffing': ['contract-vs-direct-hire', 'techs-screen-techs', 'when-your-it-person-quits'],
}
